### PR TITLE
Fix segfault when reconnecting after ChannelProtocolError

### LINKED ISSUE #11: Pidgin now crashes anytime I try send a message.

### PR DESCRIPTION
**Pull request by dequis**
Commented out the ack = 0 thing because it complained with:

    {
        "msg":"ChannelProtocolError",
        "reason":"Cannot rewind to 0, precedes last ack 10"
    }

Still don't get what this thing expects us to do. So picky.

Fixes #11, #12

### CODE REVIEW

File: libyahoo-plusplus.c [hunk 1]
```diff
@@ -1175,8 +1175,9 @@ yahoo_process_frame(YahooAccount *ya, const gchar *frame)
 				//Client ack 16 exceeds server seq 4
 				
 				ya->seq = 0;
-				ya->ack = 0;
+				//ya->ack = 0;
 				yahoo_start_socket(ya);
+				return FALSE;
```
Comment (EionRobb) [inline libyahoo-plusplus.c]: Will this leak the `parser` memory?

**Comment by EionRobb** [comment]
> Still don't get what this thing expects us to do. So picky.

It wants us to not skip ahead or fall behind unless we're supposed to :/

File: libyahoo-plusplus.c (hunk 1 above)
Comment (dequis) [inline libyahoo-plusplus.c]: Oh. It does.
